# Generated by Django 3.2.9 on 2021-11-15 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20211114_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_boolean',
            new_name='digital',
        ),
    ]
