# Generated by Django 3.2.9 on 2021-11-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=255)),
                ('away', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
            ],
        ),
    ]
