# Generated by Django 3.2.9 on 2021-11-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='competition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
