# Generated by Django 3.2.9 on 2021-12-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
